# Host Name
host_name: "eeg_stream"

# Channel Names
ch_names:
  - "Fp1"
  - "Fp2"
  - "F3"
  - "F4"

# Channel Types
ch_types: "eeg"

# Sampling Frequency
sfreq: 4

# Timeout for the connection
timeout: 10

# Define stages of the pipeline
# (low_pass, high_pass, band_pass, band_stop)
# The name of the stage must be the same as the
# keys in the step dictionary in Pipeline Builder
preprocessing_pipeline:
  - low_pass: [1]
  - high_pass: [0.1]
  - band_pass: [0.1, 1]
  - band_stop: [49, 51]

# Define keyboard mapping for events
# the keys must be the same as the ones in the
# pynput.Keyboard.Key class
keyboard_mapping:
  j: "jumping"
  w: "walking"
  r: "running"
  s: "sitting"
  page_up: "looking_up"
